
services:
  receipt-processor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receipt-processor
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    environment:
      - AI_API_KEY=${AI_API_KEY}
      - AI_API_URL=${AI_API_URL}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - receipt-network

  db:
    image: postgres:14
    container_name: receipt-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - receipt-network

networks:
  receipt-network:
    driver: bridge

volumes:
  postgres-data: